---
- name: Stop CentOS Webserver
  service: name=httpd state=stopped
  when: ansible_distribution == "CentOS"

- name: Stop Debian Webserver 
  service: name=apache2 state=stopped
  when: ansible_distribution == "Debian"
