---
- name: Start CentOS Webserver
  service: name=httpd state=started
  when: ansible_distribution == "CentOS"

- name: Start Debian Webserver 
  service: name=apache2 state=started
  when: ansible_distribution == "Debian"
