---
- name: Start Muticraft Services
  command: /home/minecraft/multicraft/bin/multicraft stop

- name: Disable IPTables
  command: /usr/bin/iptables -F

- name: Start Muticraft Services
  command: /home/minecraft/multicraft/bin/multicraft start
