---
- hosts: all
  user: root
  tasks:
     - name: Ensure needed Debian packages are present
       apt: pkg=build-essential,linux-headers-amd64,p7zip-full state=present
       when: ansible_distribution == "Debian"
       
     - name: Ensure needed RPM packages are present
       yum: name=net-tools state=present
       when: ansible_distribution == "CentOS"
       
     - name: Download & Extract VMwareTools
       unarchive:
         src: http://192.168.100.76/3rd_party/vmware/VMwareTools-9.4.0-1280544.tar.gz
         dest: /tmp/
         remote_src: True
         
     - name: Launch VMwareTools installation
       command: /tmp/vmware-tools-distrib/vmware-install.pl -d
              
     - name: Clean extracted folder
       local_action: file path={{item}} state=absent
       with_fileglob:
         - /tmp/VMwareTools*.tar.gz
         - /tmp/vmware*
