---
- hosts: all
  user: root
  tasks:
  - name: Update APT Cache
    apt: update_cache=yes
    when: ansible_distribution == "Debian"

  - name: Clear & Clean YUM Cache
    command: rm -fr /var/cache/yum/*; yum clean all
    when: ansible_distribution == "CentOS"

  - name: Announce the Upgrade
    command: echo "System Upgrade Has Started at" `date +"%I:%M %p"` | wall -n

  - name: Upgrade APT Packages
    apt: upgrade=yes
    when: ansible_distribution == "Debian"

  - name: Upgrade RPM Packages
    yum: 
      name: '*'
      state: latest
    when: ansible_distribution == "CentOS"
